SERVICIOS_CATALOGO = {
    "informe_valoracion_inmobiliaria": {
        "label": "Informe de valoración inmobiliaria",
        "categoria_servicio": "informe_pericial",
        "concepto": "Informe de valoración inmobiliaria",
        "descripcion": "Elaboración de informe de valoración conforme al objeto del encargo.",
        "incluye": "Inspección visual, análisis de documentación disponible, análisis de mercado cuando proceda y redacción de informe de valoración.",
        "no_incluye": "Tasación hipotecaria homologada ECO, levantamiento topográfico, comprobaciones registrales exhaustivas, certificados administrativos ni gestiones ante terceros.",
        "condiciones": "La valoración se emitirá conforme a la documentación disponible y a la inspección realizada.",
        "cantidad": 1.0,
        "precio_unitario": 0.0,
        "iva_porcentaje": 21.0,
    },
    "inspeccion_tecnica_vivienda": {
        "label": "Inspección técnica de vivienda",
        "categoria_servicio": "visita_tecnica",
        "concepto": "Inspección técnica de vivienda",
        "descripcion": "Inspección técnica y emisión de resumen o informe de observaciones.",
        "incluye": "Inspección visual general, revisión de elementos visibles y accesibles, identificación de incidencias observables y reportaje fotográfico básico.",
        "no_incluye": "Ensayos destructivos, comprobaciones ocultas, certificados oficiales, proyecto, dirección de obra ni valoración económica salvo contratación expresa.",
        "condiciones": "La inspección se limita a elementos visibles y accesibles en el momento de la visita.",
        "cantidad": 1.0,
        "precio_unitario": 0.0,
        "iva_porcentaje": 21.0,
    },
    "estudio_documental": {
        "label": "Estudio preliminar y análisis documental",
        "categoria_servicio": "estudio_documental",
        "concepto": "Estudio preliminar y análisis documental",
        "descripcion": "Revisión inicial de documentación y valoración técnica preliminar del encargo.",
        "incluye": "Análisis documental inicial, identificación de información necesaria y valoración preliminar de viabilidad técnica.",
        "no_incluye": "Visita técnica, informe definitivo, ensayos, mediciones instrumentales ni ratificación judicial.",
        "condiciones": "El alcance queda condicionado a la documentación facilitada por el cliente.",
        "cantidad": 1.0,
        "precio_unitario": 0.0,
        "iva_porcentaje": 21.0,
    },
    "visita_tecnica": {
        "label": "Visita técnica",
        "categoria_servicio": "visita_tecnica",
        "concepto": "Visita técnica",
        "descripcion": "Inspección técnica del inmueble o elemento objeto de análisis.",
        "incluye": "Inspección visual, toma de datos y reportaje fotográfico básico.",
        "no_incluye": "Catas, ensayos de laboratorio, medios auxiliares especiales, drones, segundas visitas ni actuaciones no previstas.",
        "condiciones": "La visita queda condicionada al acceso efectivo al inmueble y a la disponibilidad de la documentación necesaria.",
        "cantidad": 1.0,
        "precio_unitario": 0.0,
        "iva_porcentaje": 21.0,
    },
    "redaccion_informe_pericial": {
        "label": "Redacción de informe pericial",
        "categoria_servicio": "informe_pericial",
        "concepto": "Redacción de informe pericial",
        "descripcion": "Elaboración de informe pericial técnico conforme al objeto del encargo.",
        "incluye": "Análisis técnico, redacción del informe, incorporación de fotografías/anexos disponibles y entrega en PDF.",
        "no_incluye": "Ratificación judicial, ampliaciones por nueva documentación, modificaciones por estrategia procesal, traducciones ni copias impresas.",
        "condiciones": "El informe se emitirá conforme a la documentación disponible y observaciones realizadas durante la inspección.",
        "cantidad": 1.0,
        "precio_unitario": 0.0,
        "iva_porcentaje": 21.0,
    },
    "contrainforme": {
        "label": "Contrainforme técnico",
        "categoria_servicio": "extras",
        "concepto": "Contrainforme técnico",
        "descripcion": "Análisis crítico de informe técnico o pericial aportado por tercero.",
        "incluye": "Revisión del documento aportado, análisis técnico de sus conclusiones y redacción de observaciones técnicas.",
        "no_incluye": "Visita técnica, ensayos, mediciones, ratificación judicial ni elaboración de nuevo informe completo salvo contratación expresa.",
        "condiciones": "El alcance queda condicionado al informe y documentación facilitados para revisión.",
        "cantidad": 1.0,
        "precio_unitario": 0.0,
        "iva_porcentaje": 21.0,
    },
    "mediacion_asistencia_tecnica": {
        "label": "Asistencia técnica en mediación",
        "categoria_servicio": "extras",
        "concepto": "Asistencia técnica en mediación",
        "descripcion": "Asistencia técnica para reunión, mediación o negociación vinculada al encargo.",
        "incluye": "Preparación básica y asistencia a una reunión o sesión dentro del alcance pactado.",
        "no_incluye": "Nuevas sesiones, informes adicionales, ratificación judicial, desplazamientos o dietas salvo contratación expresa.",
        "condiciones": "Cualquier sesión adicional o ampliación del alcance se presupuestará aparte.",
        "cantidad": 1.0,
        "precio_unitario": 0.0,
        "iva_porcentaje": 21.0,
    },
}


SERVICIOS_CATALOGO_OPCIONES = tuple(
    (clave, servicio["label"]) for clave, servicio in SERVICIOS_CATALOGO.items()
)
