#!/bin/bash

PROJECT_DIR="/Users/carlosblanco/sistema_pericial"
RUN_APP="$PROJECT_DIR/run_app.sh"

cd "$PROJECT_DIR" || exit 1
exec /usr/bin/arch -arm64 /bin/bash "$RUN_APP" >/tmp/sistema_pericial_control_app.log 2>&1
